# Generated by Django 4.2.5 on 2023-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
